### ISSUE TITLE
[1.10.2] Do better book ??? Maybe ???

### ISSUE THREAD

**Issue by Sejoslaw** [Sejoslaw/VanillaMagic#13]

**Comment by medsal15** [comment]
There are multiple ways to do a better book:
1. Code a new item with images, etc. inside (but this mod is about coding no new items so I guess it wont be)
2. Add links (but they wont work without internet)
3. Put images and descriptions in a mod-created folder (only need to download with new updates)

**Comment by Sejoslaw** [comment]
Or I just could create a standard book with custom NBT and when the given item will be right-clicked, the custom Gui will open and stuff will happen ?

**Comment by Mach12** [comment]
That would be against the philosophy of this mod.

If you inspect the mod, you'll notice that it does not contain any of the following elements:
- Custom-NBT items
- Additional items or blocks
- New GUIs
- Additional persistent data

Creating a book with custom effects to it, or an additional GUI, would ruin the charm of the mod which consist of adding a new potential to your base gameplay elements without changing any of their code.
No code was changed in the display for an additional GUI, no sound effect was added, none of the items used gained additional attributes. Because of that, the mod feel a lot less invasive than most others and I think this aspect should be kept around.

**Comment by Sejoslaw** [comment]
After this message I won't ruin the harmony :D
Thx :)
