### ISSUE TITLE
add api and config

### ISSUE THREAD

**Issue by adoxentor** [Sejoslaw/VanillaMagic#29]
for better mod support and modpack creators.
config to disable achievements and some spells.
api to add recipes.

**Comment by Sejoslaw** [comment]
API is a good idea but I will need to think deeper how to do it.
Vanilla Magic is very compatible (I think) because it uses only vanilla Minecraft code, except for the "machines" like autocrafting or quarry, etc. They are using outside inventory (Chests) to store and get items. I made it that You can put any IInventory as input / output. 
For this achievement disabling....hmm....in Minecraft, achievements are connected, if You disable one that is needed what should happen ?
If You could tell me how You can imagine achievement disabling ?
For instance if I disable the "Pick Blaze Rod", what should happene ?

**Comment by adoxentor** [comment]
My idea is simply to add an option to remove all achievement from the mod, and for the API for a start add an option to add and change recipes. (for a modpack based around vanilla magic, with a questing mod) .

**Comment by Sejoslaw** [comment]
I will add it and concentrate on it but don't expect it soon.
BUT it will be added :)

**Comment by Sejoslaw** [comment]
As You may see I did start working on the system that will let people configure achievements via config file.
I will add all the quests to the JSON file and I will write simple "how to change values" and stuff like that :)

**Comment by Sejoslaw** [comment]
Please check version 0.16.0.0

**Comment by adoxentor** [comment]
why do you use numeric id for blocks?

**Comment by Sejoslaw** [comment]
It was easier to create ItemStack from number because You don't need to specify if it's Item or Block.

**Comment by Sejoslaw** [comment]
Added API.
